const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGOUT: 'LOGOUT',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',

    GET_TOURS:'GET_TOURS',
    GET_TOURS_LIMIT: 'GET_TOURS_LIMIT',
    GET_TOURS_UPCOMING:'GET_TOURS_UPCOMING',
    GET_TOURS_ONGOING:'GET_TOURS_ONGOING',
    GET_TOURS_ENDED:'GET_TOURS_ENDED',

    GET_USER:'GET_USER',
    GET_TOURS_LIMIT_ADMIN: 'GET_TOURS_LIMIT_ADMIN',

    GET_TEAMS_LIMIT_ADMIN: 'GET_TEAMS_LIMIT_ADMIN',

}

export default actionTypes